from typing import Iterable, Protocol
from models.contact import Contact


class ContactsRepository(Protocol):
    """Repository for the notes"""
    def add(self, contact: Contact) -> None: ...
    def get(self, name: str, default) -> Contact: ...
    def delete(self, name: str) -> None: ...
    def find(self, query: str) -> Iterable[Contact]: ...
    def all(self) -> Iterable[Contact]: ...
    def save(self, contact: Contact) -> None: ...
