from typing import Optional, Iterable, Protocol, Collection
from models.note import Note, Tag


class NotesRepository(Protocol):
    """Repository for the notes"""
    def add(self, note: Note) -> None: ...
    def get(self, note_id: int) -> Optional[Note]: ...
    def all(self) -> Iterable[Note]: ...
    def find(self, query: str) -> Iterable[Note]: ...
    def find_by_tags(self, tags: Collection[Tag]) -> Iterable[Note]: ...
    def delete(self, note_id: int) -> None: ...
    def save(self, note: Note) -> None: ...
